apiVersion: v2
name: hello-service
description: Helm chart for Hello Service using shared java-service chart
type: application
version: 0.1.0

dependencies:
  - name: java-service
    version: 1.0.0
    repository: "https://funmagsoft.github.io/helm/charts"
